//
//  SubtaskRecord.swift
//  FocusFlow
//
//  Individual step within a task, typically generated by Foundation Models.
//

import Foundation
import SwiftData

@Model
final class SubtaskRecord {
    @Attribute(.unique) var id: UUID
    var title: String
    var estimatedMinutes: Int
    var difficulty: Difficulty
    var orderIndex: Int
    var isComplete: Bool

    // MARK: - Computed Properties

    /// Scaled estimate based on user's historical pace
    /// Falls back to AI estimate if no scale factor available
    var scaledEstimateMinutes: Int {
        guard let scaleFactor = task?.estimateScaleFactor else {
            return estimatedMinutes
        }
        return max(1, Int(round(Double(estimatedMinutes) * scaleFactor)))
    }

    // MARK: - Relationships

    /// Parent task (set automatically via inverse relationship)
    var task: TaskRecord?

    // MARK: - Initialization

    init(
        title: String,
        estimatedMinutes: Int = 10,
        difficulty: Difficulty = .medium,
        orderIndex: Int = 0
    ) {
        self.id = UUID()
        self.title = title
        self.estimatedMinutes = estimatedMinutes
        self.difficulty = difficulty
        self.orderIndex = orderIndex
        self.isComplete = false
    }
}
