//
//  SubtaskRecord.swift
//  FocusFlow
//
//  Individual step within a task, typically generated by Foundation Models.
//

import Foundation
import SwiftData

enum Difficulty: String, Codable, CaseIterable {
    case easy
    case medium
    case hard
}

@Model
final class SubtaskRecord {
    @Attribute(.unique) var id: UUID
    var title: String
    var estimatedMinutes: Int
    var difficulty: Difficulty
    var orderIndex: Int
    var isComplete: Bool

    // MARK: - Relationships

    /// Parent task (set automatically via inverse relationship)
    var task: TaskRecord?

    // MARK: - Initialization

    init(
        title: String,
        estimatedMinutes: Int = 10,
        difficulty: Difficulty = .medium,
        orderIndex: Int = 0
    ) {
        self.id = UUID()
        self.title = title
        self.estimatedMinutes = estimatedMinutes
        self.difficulty = difficulty
        self.orderIndex = orderIndex
        self.isComplete = false
    }
}
